### ISSUE TITLE
Target `netstandard2.0` for c#

### ISSUE THREAD

**Issue by ShortDevelopment** [microsoft/bond#1189]
.Net-Framework v4.5 is [out of suppot](https://[devblogs.microsoft.com/dotnet/net-framework-4-5-2-4-6-4-6-1-will-reach-end-of-support-on-april-26-2022/](https://devblogs.microsoft.com/dotnet/net-framework-4-5-2-4-6-4-6-1-will-reach-end-of-support-on-april-26-2022/)) and the next best netframework version (`v4.6.2`) is already compatible with `netstandard2.0`.

_See https://github.com/microsoft/bond/issues/1188#issuecomment-1544414881_

### Tasks
 - [ ] Update internal build props
 - [ ] Update samples from `net45` to `net46`
 - [ ] Update libs to `netstandard2.0`
 - [ ] Remove conditional compilation
 - [ ] Update tests

**Comment by chwarr** [comment]
Also, update the [table in the documentation](https://github.com/microsoft/bond/blob/master/doc/src/bond_cs.md#nuget-packages).
